proje/UNI/A/urls.py
from django import views
from A import views
from django.urls import path

app_name='A'
urlpatterns = [

     path('',views.homeview.as_view() , name='homeurl'),
     path('post/<int:post_id>/<slug:post_slug>/' , views.postdetailview.as_view() ,name='posturl'),
     path('create/' , views.createpostview.as_view() , name='createurl'),
     path('like/<int:post_id>/', views.postlikeview.as_view(), name='likeurl'),
     path('dislike/<int:post_id>/', views.postdislikeview.as_view(), name='dislikeurl'),
     path('delete/<int:post_id>/', views.deletepostview.as_view(), name='deleteurl'),
     path('update/<int:post_id>/', views.postupdateformview.as_view(), name='updateurl'),
     path('reply/<int:post_id>/<int:comment_id>/' , views.postaddreplyview.as_view() ,name='reply'),


]

proje/UNI/UNI/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('A.urls' , namespace='A')),
    path('accounts/',include('accounts.urls' , namespace='accounts')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

proje/UNI/accounts/urls.py
from accounts import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name='accounts'
urlpatterns = [

     path("register/",views.RegisterView.as_view() , name='registerurl'),
     path('login/',views.loginview.as_view(),  name='loginurl'),
     path('reset/' ,views.resetpasswordview.as_view() , name='reset_password'),
     path('follow/user/<int:user_id>/' , views.followview.as_view() , name='followurl'),
     
     path('logout/',views.logoutview.as_view() ,name='logouturl'),
     path('profile/<int:user_id>/', views.profileview.as_view(), name='profileurl'),
     path('reset/done/' , views.passwordresetdoneview.as_view() , name='password_reset_done'),
     path('comfirm/<uidb64>/<token>/' , views.passwordresetconfirmview.as_view() , name='password_reset_confirm'),
     path('complete/' , views.passwordresetcomplateview.as_view() , name='password_reset_complete'),
     path('unfollow/user/<int:user_id>/' , views.unfollowview.as_view() , name='unfollowurl'),
     path('editprofile/' , views.edituserview.as_view() , name='editurl'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

proje/UNI/templates/inc/messages.html
{% if messages %}
     {% for msg in messages %}
          <p class="alert alert-{{msg.tags}}">{{ msg }}</p>
     {% endfor %}
{% endif %}

proje/UNI/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
     <div class="container-fluid">
       <a class="navbar-brand" href="#">Instagram</a>
       <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>

       <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav me-auto mb-2 mb-lg-0">
           <li class="nav-item">
               {% if request.user.is_authenticated %}
           

             <a class="nav-link active" aria-current="page" href="{% url 'A:homeurl' %}">Home</a>
           </li>
        
           <li class="nav-item">
             <a class="nav-link active" href="{% url 'accounts:profileurl' request.user.id %}">Profile</a>
           </li>
           <li class="nav-item">
            <a class="nav-link active" href="{% url 'accounts:logouturl' %}">logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'A:createurl' %}">create post </a>
          </li>
        
           {% else %}
           <li class="nav-item">
               <a class="nav-link active" href="{% url 'accounts:loginurl' %}">Login</a>
           </li>
        
           <li class="nav-item">
               <a class="nav-link active" href="{% url 'accounts:registerurl' %}">Register</a>
           </li>
        
           {% endif %}
         {% if request.user.is_authenticated %}

         </ul>


         <form class="d-flex" method="get">
           <input style="margin-right: 5px;" name="search"  type="text" class="form-control ">
          <input  class="btn btn-success" value="serch" type="submit">
     </form>
    
         {% endif %}

       </div>
     </div>
   </nav>