proje/UNI/A/urls.py
from django import views
from A import views
from django.urls import path

app_name='A'
urlpatterns = [

     path('',views.homeview.as_view() , name='homeurl'),
     path('post/<int:post_id>/<slug:post_slug>/' , views.postdetailview.as_view() ,name='posturl'),
     path('create/' , views.createpostview.as_view() , name='createurl'),
     path('like/<int:post_id>/', views.postlikeview.as_view(), name='likeurl'),
     path('dislike/<int:post_id>/', views.postdislikeview.as_view(), name='dislikeurl'),
     path('delete/<int:post_id>/', views.deletepostview.as_view(), name='deleteurl'),
     path('update/<int:post_id>/', views.postupdateformview.as_view(), name='updateurl'),
     path('reply/<int:post_id>/<int:comment_id>/' , views.postaddreplyview.as_view() ,name='reply'),


]

proje/UNI/UNI/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('A.urls' , namespace='A')),
    path('accounts/',include('accounts.urls' , namespace='accounts')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

proje/UNI/accounts/urls.py
from accounts import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name='accounts'
urlpatterns = [

     path("register/",views.RegisterView.as_view() , name='registerurl'),
     path('login/',views.loginview.as_view(),  name='loginurl'),
     path('reset/' ,views.resetpasswordview.as_view() , name='reset_password'),
     path('follow/user/<int:user_id>/' , views.followview.as_view() , name='followurl'),
     
     path('logout/',views.logoutview.as_view() ,name='logouturl'),
     path('profile/<int:user_id>/', views.profileview.as_view(), name='profileurl'),
     path('reset/done/' , views.passwordresetdoneview.as_view() , name='password_reset_done'),
     path('comfirm/<uidb64>/<token>/' , views.passwordresetconfirmview.as_view() , name='password_reset_confirm'),
     path('complete/' , views.passwordresetcomplateview.as_view() , name='password_reset_complete'),
     path('unfollow/user/<int:user_id>/' , views.unfollowview.as_view() , name='unfollowurl'),
     path('editprofile/' , views.edituserview.as_view() , name='editurl'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

proje/UNI/accounts/models.py
from distutils.command.upload import upload
from django.db import models
from django.contrib.auth.models import User


class Relation (models.Model):
     from_user = models.ForeignKey(User , on_delete=models.CASCADE , related_name='followers')
     to_user = models.ForeignKey(User , on_delete= models.CASCADE , related_name='following')
     created = models.DateTimeField(auto_now_add=True)
     
     def __str__(self):
          return f'{self.from_user}following {self.to_user}'
           

class profile(models.Model):
    user=models.OneToOneField(User , on_delete=models.CASCADE ,related_name='profile' )
    age=models.PositiveSmallIntegerField(default=0)
    bio=models.TextField(null=True , blank=True)
    image = models.ImageField(null=True,upload_to = 'image_profile/')
    
    def __str__(self) :
         return f'{self.user}  ... {self.age}' 
    

    

proje/UNI/accounts/forms.py
from .models import profile
from django import forms





class RegisterForm(forms.Form):
     username=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
     email=forms.CharField(widget=forms.EmailInput(attrs={'class':'form-control'}))
     password1=forms.CharField(label="password", widget=forms.PasswordInput(attrs={'class':'form-control'}))
     password2=forms.CharField(label='password again',widget=forms.PasswordInput(attrs={'class':'form-control'}))


class loginform (forms.Form):
     username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
     password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))



class edituserform(forms.ModelForm):
     email = forms.EmailField(widget=forms.EmailInput(attrs={'calss':'form-control'}))
     class Meta:
          model = profile
          fields = ('age' , 'bio','image')

proje/UNI/accounts/views.py
from re import I
from django.contrib import messages
from pyexpat.errors import messages
from django.shortcuts import render
from django.views import View
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import login ,authenticate ,logout
from django.http import HttpResponse
from  .forms import *
from django.contrib.auth import views as auth_views
from django.urls import  reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Relation,profile
from accounts.models import Relation
from A.models import postmodel


class RegisterView(View):
     def dispatch(self, request, *args, **kwargs):
          if request.user.is_authenticated:
               return redirect('A:homeurl')
          return super().dispatch(request, *args, **kwargs)

     def get(self,request):
          form=RegisterForm()
          return render(request, 'accounts/register.html',{'form':form})

     def post (self , request):
          
          cd = request.POST
          if User.objects.filter(email=cd['email']).exists():
               messages.info(request,'email warniing','info')
               
               return redirect ('accounts:registerurl')



          if cd ['password'] == cd ['password2']:
               try:
                    user = User.objects.create_user(email = cd['email'] , username = cd['username'] , password = cd['password'])
                    profile.objects.create(user = user)
                    messages.success(request,'user registered','success')
                    return redirect ('accounts:loginurl')
               except:
                    messages.info(request , 'Error' , 'info')
                    return redirect ('accounts:registerurl')

          else:
               messages.info(request , 'username password not math' , 'info')
               return redirect ('accounts:registerurl')


class loginview (View):
     def dispatch(self , request , *args , **kwargs):
          if request.user.is_authenticated:
               return redirect('A:homeurl')
          return super().dispatch(request, *args , **kwargs)

     def get (self , request):
          form = loginform
          return render(request , 'accounts/login.html' , {'form':form}) 

     def post(self , request ):
          username = request.POST ['username']
          password = request.POST ['password']
          user = authenticate(request , username=username, password=password)
          if user is not None:
               login(request , user)
               return redirect('A:homeurl')
          messages.info(request, 'username or password invalid' , 'info')
          return redirect('accounts:logouturl')
          




class resetpasswordview(auth_views.PasswordResetView):
     template_name: 'accounts/password_reset_form.html'
     success_url=reverse_lazy('accounts:password_reset_done')
     email_template_name='accounts/password_reset_email.html'


class logoutview (LoginRequiredMixin , View):

     def get (self , request):
          logout(request)
          messages.success(request , 'logout successful' , 'success')
          return redirect ('accounts:loginurl')


class profileview(LoginRequiredMixin , View):
     def get (self , request , user_id ):
          is_following = False
          user = User.objects.get(pk= user_id)
          posts = postmodel.objects.filter(user=user)
          relation =Relation.objects.filter(from_user= request.user , to_user= user)
          if relation.exists():
               is_following = True
          return render (request , 'accounts/profile.html' , {'user':user , 'posts':posts , 'is_following':is_following})



class resetpasswordview(auth_views.PasswordResetView):
     template_name='accounts/password_reset_form.html'
     success_url=reverse_lazy('accounts:password_reset_done')
     email_template_name='accounts/password_reset_email.html'


class passwordresetdoneview(auth_views.PasswordResetDoneView):
     template_name='accounts/password_reset_done.html'


class passwordresetconfirmview(auth_views.PasswordResetConfirmView):
     template_name='accounts/password_reset_confirm.html'
     success_url=reverse_lazy('accounts:password_reset_complete')


class passwordresetcomplateview(auth_views.PasswordResetCompleteView):
     template_name='accounts/password_reset_complete.html'


class followview( LoginRequiredMixin , View):
     def get (self , request , user_id  ):
          
          # post = postmodel.objects.get(id = post_id)
          user = User.objects.get(id = user_id)
          relation = Relation.objects.filter(from_user = request.user , to_user = user)
          if relation.exists():
               messages.error(request , 'you are already following this user;', 'danger')
          else:
               Relation.objects.create(from_user = request.user , to_user = user)
               messages.success(request , 'you following this user' , 'info')
          return redirect ('accounts:profileurl' ,user_id) 
          



class unfollowview (LoginRequiredMixin , View):
     def get (self , request , user_id ):
          # post = postmodel.objects.get(id = post_id)

          user = User.objects.get(id = user_id)
          relation = Relation.objects.filter(from_user = request.user , to_user = user)
          if relation.exists():
               relation.delete()
               messages.success(request , 'you unfollowing this user' , 'info' )
          else:
               messages.error(request , 'you are not following this user' , 'danger')
          return redirect ('accounts:profileurl' ,user_id) 


class edituserview(LoginRequiredMixin , View):
     form_class = edituserform

     def get(self , request):
          form = self.form_class(instance = request.user.profile , initial ={'email':request.user.email})
          return render(request , 'accounts/editprofile.html' , {'form':form})
          

     def post (self , request):
          form = self.form_class(request.POST,request.FILES , instance=request.user.profile)
          
          if form.is_valid:
               
               form.save()
               request.user.email = form.cleaned_data['email']
               request.user.save()
               messages.success(request , 'edit successful' , 'success')
          return redirect ('accounts:profileurl' , request.user.id)

proje/UNI/accounts/templates/accounts/editprofile.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
     <div class="row">
          <div class="col-md-4 mx-auto">
               <form method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="edit">
               </form> 
          </div>
     </div>
</div>
   
{% endblock %}

proje/UNI/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}



{% block title %} LOGIN {% endblock %}
<link rel="stylesheet" href="{% static 'accounts/css/login.css%'}">
{% block body %} 
<div class="container justify-content-cente ">
     <div class="row ">
          <form action="" method="post" class="col-md-3 mx-auto">
               {% csrf_token %}
               <h3>login</h3>

               <div class="form-group">
                    <label for="exampleInputEmail1">UserName</label>
                    <input type="text" class="form-control" name="username" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter username" >
                    
               </div> 
                    
               <div class="form-group m-b-2">
                    <label for="exampleInputPassword1">Password</label> 
                    <input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder="Password"> 
               </div> 
                    
                    <button type="submit" class="btn btn-primary mt-2">Submit</button>   <br>
               <a  href="{% url 'accounts:reset_password' %}">Forgot Password!</a>
          </form>
     </div>
</div>
{% endblock %}

proje/UNI/accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% block body %}
     <p> your password changed. </p>
{% endblock %}

proje/UNI/accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block body %}
     {% if validlink %}
     <form action="" method="post">
          {% csrf_token %}
          {{form.as_p}}
          <input type="submit" value="">
     {% else %}
     <p> this link is not valid, please try again.</p>
     {% endif %}
     </form>
{% endblock %}

proje/UNI/accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block body %}
     <h3> we send your email </h3>
{% endblock %}

proje/UNI/accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

proje/UNI/accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}

{% block body %}
     <form action="" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="send">
     </form>
{% endblock %}

proje/UNI/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block title %} profile {% endblock %}


     <link rel="stylesheet" href="{% static 'accounts/css/profile.css'%}">


{% block body %} 

     


     



     {% if request.user.id != user.id and not is_following %}
          <a class="btn btn-primary mb-2"  href="{% url 'accounts:followurl' user.id %}">follow</a>
     {% elif request.user.id != user.id and  is_following %}
          <a class="btn btn-primary mb-2 "  href="{% url 'accounts:unfollowurl' user.id %}">unfollow</a>
     {% endif %}
   {% if request.user.id == user.id %}
     <div class="card">
          <div class="container">
               <div class="profile" style="display: flex; margin: 20px; padding: 10px;">
                    <div class="image" style="width: 100px; height: 100px; ">
                         {% if user.profile.image %}
                              <a href="{{user.profile.image.url}}">  <img src="{{user.profile.image.url}}" style="width: 100%; height: 100%; border-radius: 50px; margin: 10px;"></a>
                         {% else %}
                         <img src="{% static 'accounts/img/profile.png'%}" alt="my img" style="width: 100%; height: 100%; border-radius: 50px; margin: 10px;">
                              {% endif %}
                    </div>
                    <div class="title" style="width: auto; padding: 0;  height: 100px; margin-left: 30px;">
                         <h6 style="">{{user.email}}</h6>
                         <h6 style="">{{user.username}}</h6>
                         <h6 style="">{{user.profile.age}}</h6>
                         {% if request.user.id == user.id %}
         
          <a href="{% url 'accounts:editurl' %}" class="btn btn-primary">edit</a>
     {% endif %}

                        
                    
                    </div>
               </div>
                 
                    

             
          </div>
        
     </div>
     {% endif %}
     {% if posts %}
     <p class="alert alert-primary mt-5">your posts</p>

     <div class="card">

          <div class="container">

               <div class="row">
                    {% for postmodel in posts %}
                    
                         <div class="col-md-4">
                              <div class="body-post shadow mt-3 mb-3" style="padding: 5px;">
                              <div >
                                   <a style="text-decoration:none ; text-align: center;" href="{{postmodel.get_absolute_url}}" >
                                   
                                        <img src="{{postmodel.img.url}}" style="width: 100%; height: 300px; " >
                                   
                                        <p style="color: black ;" class="mt-2 mb-3" > title: {{postmodel.title}} </p>
                                      
          
                                   </a>
                                 
                                   </div>
                              </div>
                         </div>
                        
                        
                    {% endfor %}

               </div>
          </div>
        
     </div>
     {% endif %}
        <!-- <a  href="{{postmodel.get_absolute_url}}" style="text-decoration: none; color: black;"><img src="{{postmodel.img.url}}" style="width: 300px; height: 300px; margin-top: 20px ;" class="" >
                         <p style="margin-top: 5px; "><strong> user created: </strong> {{postmodel.user}}</p>
                         <p style="margin-top: 5px;"><strong> post informations:</strong> {{postmodel.body}}</p>
                         <p style="margin-top: 5px;"><strong>post created:</strong> {{postmodel.created | timesince}}</p>
                         <p style="margin-top: 5px;"><strong>last updated: </strong>{{postmodel.updated | timesince}}</p> 

                         </a> -->
                    
                        
{% endblock %}

proje/UNI/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block title %} REGISTER {% endblock %}

{% block body %} 

<div class="container justify-content-cente">
     <div class="row ">
          
          <form action="" method="post" class="col-md-3 mx-auto">
               {% csrf_token %}
               <h3>Register</h3>
               <div class="form-group">
                    <label for="exampleInputEmail1">UserName</label>
                    <input type="text" class="form-control" name="username" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter username" >
                    <label for="exampleInputEmail1">Email</label>
                    <input type="email" class="form-control" name="email" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" >
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> </div> <div class="form-group">
                    <label for="exampleInputPassword1">Password</label> 
                    <input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder="Password"> </div>
                    <label for="exampleInputEmail1">again Password</label>
                    <input type="password" class="form-control" name="password2" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter again password" > 
                    <button type="submit" class="btn btn-primary mt-2">Submit</button>   <br>
          </form>
     </div>
</div>

{% endblock %}