proje/UNI/A/urls.py
from django import views
from A import views
from django.urls import path

app_name='A'
urlpatterns = [

     path('',views.homeview.as_view() , name='homeurl'),
     path('post/<int:post_id>/<slug:post_slug>/' , views.postdetailview.as_view() ,name='posturl'),
     path('create/' , views.createpostview.as_view() , name='createurl'),
     path('like/<int:post_id>/', views.postlikeview.as_view(), name='likeurl'),
     path('dislike/<int:post_id>/', views.postdislikeview.as_view(), name='dislikeurl'),
     path('delete/<int:post_id>/', views.deletepostview.as_view(), name='deleteurl'),
     path('update/<int:post_id>/', views.postupdateformview.as_view(), name='updateurl'),
     path('reply/<int:post_id>/<int:comment_id>/' , views.postaddreplyview.as_view() ,name='reply'),


]

proje/UNI/UNI/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('A.urls' , namespace='A')),
    path('accounts/',include('accounts.urls' , namespace='accounts')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

proje/UNI/accounts/urls.py
from accounts import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name='accounts'
urlpatterns = [

     path("register/",views.RegisterView.as_view() , name='registerurl'),
     path('login/',views.loginview.as_view(),  name='loginurl'),
     path('reset/' ,views.resetpasswordview.as_view() , name='reset_password'),
     path('follow/user/<int:user_id>/' , views.followview.as_view() , name='followurl'),
     
     path('logout/',views.logoutview.as_view() ,name='logouturl'),
     path('profile/<int:user_id>/', views.profileview.as_view(), name='profileurl'),
     path('reset/done/' , views.passwordresetdoneview.as_view() , name='password_reset_done'),
     path('comfirm/<uidb64>/<token>/' , views.passwordresetconfirmview.as_view() , name='password_reset_confirm'),
     path('complete/' , views.passwordresetcomplateview.as_view() , name='password_reset_complete'),
     path('unfollow/user/<int:user_id>/' , views.unfollowview.as_view() , name='unfollowurl'),
     path('editprofile/' , views.edituserview.as_view() , name='editurl'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

proje/UNI/A/models.py
from turtle import title
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class postmodel(models.Model):
     user = models.ForeignKey(User,on_delete=models.CASCADE )
     title = models.CharField(max_length=50,null=True)
     price = models.IntegerField(default=0)
     body = models.TextField(max_length=100)
     slug = models.SlugField()
     created = models.DateTimeField(auto_now_add=True)
     updated = models.DateTimeField(auto_now=True)
     img =models.ImageField(upload_to='folderimages/',null=True)

     class Meta:
        ordering = ('-created',)

     def __str__(self):
        return self.slug

     def get_absolute_url(self):
        return reverse('A:posturl' , args=(self.pk , self.slug))

     def like_count(self):
        return self.plike.count()

     def user_can_like(self , user):
        user_like=user.ulike.filter(post=self)
        if user_like.exists():
            return True
        return False
                     

class Comment (models.Model):
   user = models.ForeignKey(User , on_delete=models.CASCADE , related_name=  'ucomments')
   post = models.ForeignKey(postmodel , on_delete=models.CASCADE , related_name='pcomments')
   # reply= models.ForeignKey('self' , on_delete=models.CASCADE , related_name='rcomments' , blank=True , null=True)
   # is_reply = models.BooleanField(default=False)
   body = models.TextField(max_length=400)
   created = models.DateTimeField(auto_now_add=True)

   def __str__(self):
      return f'{self.user} - {self.body [:30]}'



class Like(models.Model):
      user=models.ForeignKey(User , on_delete=models.CASCADE, related_name='ulike')
      post=models.ForeignKey(postmodel , on_delete=models.CASCADE , related_name='plike')

      def __str__(self):
        return f'{self.user}liked{self.post.slug}'

proje/UNI/A/forms.py
from dataclasses import fields
from pyexpat import model
from tkinter import Widget
from .models import Comment, postmodel
from django import forms

from A.models import postmodel


class searchform(forms.Form):
     search=forms.CharField()



class commentcreateform (forms.ModelForm):
     class Meta:
          model = postmodel
          fields = ('body', 'img')


class commentreplyform(forms.ModelForm):
     class  Meta:
          model = Comment
          fields = ('body',)
          Widgets ={
               'body':forms.Textarea(attrs={'class':'form-control'})  
          }



class postcreateupdateform(forms.ModelForm):
     class Meta:
          model = postmodel
          fields = ('title','body' , 'img')

proje/UNI/A/views.py
from django import views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from A.forms import searchform , commentcreateform , commentreplyform , postcreateupdateform
from accounts.models import Relation
from .models import postmodel , Like ,Comment
from django.shortcuts import render
from django.views import View
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.shortcuts import redirect, render
from django.utils. text import slugify


class homeview ( LoginRequiredMixin,View):
     form_class = searchform
     
     def get(self,request ):
         
          posts = postmodel.objects.all()
          if request.GET.get('search'):
               posts = posts.filter(slug__contains=request.GET['search'])
          return render(request,'home/home.html', {'posts': posts , 'form':self.form_class})
        
     
     


class postdetailview (View):
     form_class = commentcreateform
     form_class_reply = commentreplyform
     

     def setup(self, request ,*args, **kwargs):
          self.post_instance = get_object_or_404(postmodel , pk = kwargs['post_id'] , slug = kwargs['post_slug'])
          return super().setup(request , *args , **kwargs)

     
     def get (self , request , post_id , post_slug):
          posts = postmodel.objects.get(pk = post_id , slug = post_slug)
          
          comments = posts.pcomments.all()
          like = Like.objects.filter(user=request.user,post=posts).exists()
          relation = Relation.objects.filter(from_user=request.user , to_user =self.post_instance.user ).exists()
          like_count = Like.objects.filter(post = posts).count()
          
          can_like = True
          can_fallow =True
          if request.user.is_authenticated and relation:
               can_fallow = False
          if request.user.is_authenticated and like:
               can_like = False
          return render(request , 'home/details.html' , {'posts':posts , 'comments':comments   , 'canlike':can_like,'canfallow':can_fallow,'like_count':like_count})


     def post(self , request , *args , **kwargs):
          comment =request.POST['comment']
          Comment.objects.create(user = request.user,post =self.post_instance,body=comment )
          messages.success(request , 'your comment submit successful' , 'success')

          return redirect('A:posturl' , self.post_instance.id , self.post_instance.slug)

          # form = self.form_class(request.POST)
          # if form.is_valid:
          #      new_comment = form.save(commit = False)
          #      new_comment.user = request.user
          #      new_comment.post = self.post_instance
          #      new_comment.save()
          #      messages.success(request , 'your comment submit successful' , 'success')
          #      return redirect('home:posturl' , self.post_instance.id , self.post_instance.slug)

     
class createpostview (LoginRequiredMixin , View):
     form_class= postcreateupdateform

     def get(self , request , *args , **kwargs):
          form = self.form_class
          return render(request ,'home/create.html' , {'form':form})

     def post (self , request , *args , **kwargs):
          cd = request.POST
          
          img = request.FILES
          post = postmodel.objects.create(user= request.user,title = cd['title'],
          body = cd['caption'],img=img['img']
          )
          post.slug=slugify(cd['caption'])[:30]
          post.save()
          messages.success(request,'created post successfull' , 'success')
          return redirect('A:posturl', post.id ,post.slug)

          
          # form = self.form_class(request.POST,request.FILES['img'])
          # if form.is_valid():
               
          #      new_post = form.save(commit=False)
          #      new_post.slug= slugify(form.cleaned_data['body'][:30])
          #      new_post.user=request.user
          #      new_post.save()
               
          #      messages.success(request,'created post successfull' , 'success')
          #      return redirect('A:posturl', new_post.id ,new_post.slug)


class postlikeview(LoginRequiredMixin , View):
     def get (self, request, post_id):
          post=get_object_or_404(postmodel ,id=post_id)
          like=Like.objects.filter(post=post , user=request.user)
          if like.exists():
               messages.error(request, 'You liked it before' ,'danger')
          else:
               Like.objects.create(post=post, user=request.user)
               messages.success(request , 'liked successfully' , 'success')
          return redirect('A:posturl' , post.id , post.slug)

class postdislikeview(LoginRequiredMixin,View):
     def get (self, request, post_id):
          post=get_object_or_404(postmodel ,id=post_id)
          like=Like.objects.filter(post=post , user=request.user)
          if like.exists():
               like.delete()
               messages.error(request, 'You disliked' ,'danger')
          else:
              
               messages.success(request , 'you not like this post' , 'success')
          return redirect('A:posturl' , post.id , post.slug)


class deletepostview(LoginRequiredMixin , View):
     def get(self , request , post_id):
          post= postmodel.objects.get(pk=post_id)
          if post.user.id == request.user.id:
               post.delete()
               messages.success(request, 'deleted post successfull' , 'success')

          else:
               messages.error(request , 'You can not delete the post')
          return redirect('A:homeurl')


class postupdateformview(LoginRequiredMixin, View):
     form_class=postcreateupdateform
     def setup(self, request, *args, **kwargs):
          self.post_instance=postmodel.objects.get(pk=kwargs['post_id'])
          return super().setup(request, *args, **kwargs)
     
     def dispatch(self, request, *args, **kwargs):
          post = self.post_instance
          if not post.user.id == request.user.id:
               messages.error(request, 'Update failed' ,'danger')
               return redirect('A:homeurl')
          return super().dispatch(request, *args, **kwargs)


     def get(self , request, *args , **kwargs):
          post= self.post_instance
          form= self.form_class(instance=post)
          
          return render(request , 'home/update.html' , {'form':form})
    
    
     def post(self , request, *args ,**kwargs):
          post=self.post_instance
          form=self.form_class(request.POST,request.FILES , instance=post)
          if form.is_valid:
               new_post=form.save(commit=False)
               new_post.slug=slugify(form.cleaned_data['body'][:30])
               new_post.save()
               messages.success(request,'updated successfull' , 'success')
               return redirect('A:posturl' , post.id , post.slug)
         
class postaddreplyview(LoginRequiredMixin, View):
     form_class= commentreplyform

     def post(self , request , post_id , comment_id):
          post=get_object_or_404(postmodel,id=post_id)
          comment=get_object_or_404(Comment , id=comment_id)
          form=self.form_class(request.POST)
          if form.is_valid():
               reply=form.save(commit=False)
               reply.user=request.user
               reply.post=post
               reply.reply=comment
               reply.is_reply=True
               reply.save()
               messages.success(request, 'reply is successfully' , 'success')
          return redirect('A:posturl' , post.id , post.slug)

proje/UNI/A/templates/home/create.html
{% extends 'base.html' %}

{% block title %} create post {% endblock %}

{% block body %}
<div class="container">
     <div class="row">
          <div class="col-md-4 mx-auto">
               <form enctype="multipart/form-data" action="" method="post" novalidate>
                    {% csrf_token %}
                    <label for="">title:</label>
                    <input name="title" placeholder="title" type="text" class="form-control" >
                    <label for="">caption:</label>
                    <textarea  placeholder="caption" name="caption" id="" cols="10" rows="10" class="form-control" ></textarea>
                    <input name="img" type="file" class="form-control mt-2 mb-2">
                    <input type="submit" class="btn btn-primary" value="create">
               </form>
          </div>
     </div>
</div>
   
{% endblock %}

proje/UNI/A/templates/home/details.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} detail {% endblock %}

{% block body %}


     

     <div class="container">
          <div class="row ">
               

               <div class="col-md-6 mx-auto shadow">

                    <img src="{{posts.img.url}}" style="width: 100%; padding: 5px;" alt="">
                    <p class="mt-2" >users created: <a style="font-size: 20px; text-decoration: none;" href="{% url 'accounts:profileurl' posts.user.id  %}">{{posts.user}} </a>
                       
                         </p>

                    <p class="mt-2" >title: {{posts.title}}</p>
                    <p  >caption: {{posts.body}}</p>
                    <p >last updated: {{posts.updated}}</p>
                    {% if canlike == True %}
                         <a href="{% url 'A:likeurl' posts.id %}" class="btn btn-primary mb-2"> Like {{like_count}}</a>
                    {% else  %}
                    
                         <a href="{% url 'A:dislikeurl' posts.id %}" class="btn btn-info mb-2"> disLike {{like_count}}</a>
                         
                    {% endif %}
                    {% if user.id == posts.user.id %}
                    <a href="{% url 'A:deleteurl' posts.id %}" class="btn btn-danger  mb-2">delete</a>
                   <a href="{% url 'A:updateurl' posts.id %}" class="btn btn-info  mb-2">update</a> 
                   {% endif %}


               </div>
               

          </div>
     </div>
     <div class="container mt-5">
          <div class="row">
               <div class="col-md-4 mx-auto">
               <form action="" method="post">
                    {% csrf_token %}
                    <textarea name="comment" class="form-control"  placeholder="Your Comment: " id="exampleFormControlTextarea1" rows="3"></textarea>
                    <input class="btn btn-primary mt-2" value=" Comment"  type="submit">

               </form>
          </div>
          </div>
     </div>
     <div class="container mt-5">
          <div class="row">
               <div class="col-md-4 mx-auto">
               {% for comment in comments %}
                    <p style="word-wrap: break-word;" class="alert alert-info">{{comment.body}}</p>
               {% endfor %}
          </div>
          </div>
     </div>




     
 


{% endblock %}

proje/UNI/A/templates/home/home.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %} HOME {% endblock %}

{% block body %} 
     <div class="container">
          <div class="row mx-auto">
               {% for postmodel in posts %}
               <div class="col-md-4">
                    <div class="body-post shadow mt-3" style="padding: 5px;">
                    <div >
                         <a style="text-decoration:none ; text-align: center;" href="{{postmodel.get_absolute_url}}" >
                         
                              <img src="{{postmodel.img.url}}" style="width: 100%; height: 300px; " >
                         
                              <p style="color: black ;" class="mt-2" > title: {{postmodel.title}} </p>

                         </a>
                       
                         </div>
                    </div>
               </div>
              
               
               {% endfor %}
          </div>
     </div>
{% endblock %}

proje/UNI/A/templates/home/update.html
{% extends 'base.html' %}

{% block title %} update post {% endblock %}

{% block body %}
     <form action="" method="post" enctype="multipart/form-data" novalidate>
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="update">
     </form>
{% endblock %}